version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY:-}instabot-backend:${VERSION:-latest}
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - shared-network
      - instabot-internal
    environment:
      - NODE_ENV=production
      - PORT=3000
      - INSTAGRAM_APP_ID=${INSTAGRAM_APP_ID}
      - INSTAGRAM_APP_SECRET=${INSTAGRAM_APP_SECRET}
      - INSTAGRAM_REDIRECT_URI=https://api.instabot.wbcheap.ru/auth/callback
      - WEBHOOK_VERIFY_TOKEN=${WEBHOOK_VERIFY_TOKEN}
      - FRONTEND_URL=https://instabot.wbcheap.ru
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        # Labels для идентификации сервиса в NPM
        - "app=instabot"
        - "tier=backend"
        - "domain=api.instabot.wbcheap.ru"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  frontend:
    image: ${DOCKER_REGISTRY:-}instabot-frontend:${VERSION:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=https://api.instabot.wbcheap.ru
    networks:
      - shared-network
      - instabot-internal
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        # Labels для идентификации сервиса в NPM
        - "app=instabot"
        - "tier=frontend"
        - "domain=instabot.wbcheap.ru"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  # Внешняя сеть для связи с Nginx Proxy Manager
  shared-network:
    external: true
  # Внутренняя сеть для связи между сервисами
  instabot-internal:
    driver: overlay
    attachable: true
